
export const FETCHING_PETS = 'FETCHING_PETS';
export const RECVD_PETS = 'RECVD_PETS';

export const FETCHING_VETS = 'FETCHING_VETS';
export const RECVD_VETS = 'RECVD_VETS';

export const FETCHING_APPTS = 'FETCHING_APPTS';
export const RECVD_APPTS = 'RECVD_APPTS';
export const ERR_SAVING_APPT = 'ERR_SAVING_APPT';
export const ACK_ERR_SAVING_APPT = 'ACK_ERR_SAVING_APPT';
